#!/bin/bash


APACHESITECONF=/etc/apache2/sites-enabled/000-default

# modify apache config to point to new startpage
if [ -f ${APACHESITECONF}  ]; then
    sed -i "s/apache2-default/linuxmuster-default/g" ${APACHESITECONF}
    sed -i "s/paedml-default/linuxmuster-default/g" ${APACHESITECONF}
fi

if [ -d /var/www/paedml-default ]; then
    rm -rf /var/www/paedml-default
fi

exit 0
